<?php
/** @var \MageSuite\SuccessPageOrderDetails\ViewModel\Checkout\Success\Order $viewModel */
$viewModel = $block->getViewModel();
$order = $viewModel->getOrder();
$orderId = $order->getRealOrderId();
?>
<button class="cs-last-order-details__button">
    <span><?= /* @noEscape */ __('See order details'); ?></span>
</button>

<div
    class="cs-last-order-details__modal"
    data-bind="mageInit: {
        'Magento_Ui/js/modal/modal':{
        'type': 'popup',
        'title': '<?= $block->escapeHtml(__('Order: %1', $orderId), ['span']); ?>',
        'trigger': '.cs-last-order-details__button',
        'responsive': true,
        'modalLeftMargin': 0,
        'innerScroll': true,
        'buttons': [],
        'focus': '.cs-last-order-details__modal .action-close'
    }}"
    style="display: none"
>
    <div data-role="content">
        <?=  $block->getChildHtml(); ?>
    </div>
</div>
