<?php
/** @var \Creativestyle\CustomizationHaarShop\ViewModel\Checkout\Success\Order $viewModel */
$viewModel = $block->getViewModel();
$paymentMethod = $viewModel->getPaymentMethod();
$billingAddress = $viewModel->getBillingAddress();
$billingTelephoneNumber = $billingAddress->getTelephone()
?>

<?php if ($billingAddress): ?>
    <div class="cs-last-order-details__box">
        <span class="cs-last-order-details__box-title"><?= __('Billing Address'); ?></span>
        <div class="cs-last-order-details__box-content">
            <address><?= $billingAddress->getName() ?><br>
                <?php if (!empty($billingAddress->getCompany())):?>
                    <?= $billingAddress->getCompany() ?><br>
                <?php endif; ?>
                <?= $viewModel->getStreetFull($billingAddress->getStreet()) ?><br>
                <?= $billingAddress->getCity() ?>, <?= $billingAddress->getPostcode() ?><br>
                <?= $viewModel->getCountryByCode($billingAddress->getCountryId()) ?>
                <?php if (!empty($billingTelephoneNumber)):?>
                <br>
                T: <a href="tel:<?= $billingTelephoneNumber ?>"><?= $billingTelephoneNumber ?></a>
                <?php endif; ?>
            </address>
        </div>
    </div>
<?php endif; ?>

<?php if (!empty($paymentMethod)): ?>
    <div class="cs-last-order-details__box">
        <span class="cs-last-order-details__box-title"><?= __('Payment Method'); ?></span>
        <div class="cs-last-order-details__box-content">
            <span class="cs-last-order-details__payment-method">
                <?= $paymentMethod ?>
            </span>
        </div>
    </div>
<?php endif; ?>
