<?php
/** @var \Creativestyle\CustomizationHaarShop\ViewModel\Checkout\Success\Order $viewModel */
$viewModel = $block->getViewModel();
$shippingAddress = $viewModel->getShippingAddress();
$shippingMethod = $viewModel->getShippingMethod();
$shippingTelephoneNumber = $shippingAddress->getTelephone();

?>

<?php if ($shippingAddress): ?>
    <div class="cs-last-order-details__box">
        <span class="cs-last-order-details__box-title"><?= __('Shipping address'); ?></span>
        <div class="cs-last-order-details__box-content">
            <address><?= $shippingAddress->getName() ?><br>
                <?php if (!empty($shippingAddress->getCompany())):?>
                    <?= $shippingAddress->getCompany() ?><br>
                <?php endif; ?>
                <?= $viewModel->getStreetFull($shippingAddress->getStreet()) ?><br>
                <?= $shippingAddress->getCity() ?>, <?= $shippingAddress->getPostcode() ?><br>
                <?= $viewModel->getCountryByCode($shippingAddress->getCountryId()) ?>
                <?php if (!empty($shippingTelephoneNumber)):?>
                <br>
                T: <a href="tel:<?= $shippingTelephoneNumber ?>"><?= $shippingTelephoneNumber ?></a>
                <?php endif; ?>
            </address>
        </div>
    </div>
<?php endif; ?>

<?php if (!empty($shippingMethod)): ?>
    <div class="cs-last-order-details__box">
        <span class="cs-last-order-details__box-title"><?= __('Shipping Method'); ?></span>
        <div class="cs-last-order-details__box-content"><?= $shippingMethod ?></div>
    </div>
<?php endif; ?>
